
# github-pages mandatory configuration
domain: czarnewski.github.io
url: https://czarnewski.github.io/sco-community
baseurl: /sco-community
repository: czarnewski/sco-community

# Build settings
markdown: kramdown
# theme: minima

# Name of the website
title: ELIXIR SCO Community

# Where things are
layouts_dir: ./_layouts
includes_dir: ./_includes


defaults:
  - values:
      logosnav: true


plugins:
  - jemoji

menu:
  - title: ABOUT US
    url: about_us
    submenu:
      - title: Join Us
        url: training
      - title: Contact
        url: training

  - title: TRAINING
    url: training

  - title: TOOLS
    url: tools

  - title: DATA
    url: data
    
  - title: FAQ
    url: faq



avatar: "./logos/SCO.png"
