layouts_dir: ./layouts
includes_dir: ./includes


defaults:
  - values:
      logosnav: true


plugins:
  - jemoji

menu:
  - title: About Us
    url: about_us
  - title: Training
    url: traning
  - title: Tools
    url: tools
  - title: Standards
    url: standards
  - title: FAQ
    url: faq



avatar: "./logos/SCO.png"
