# Build settings
markdown: kramdown
theme: minima

# Name of the website
title: ELIXIR SCO Community

# Where things are
layouts_dir: ./_layouts
includes_dir: ./_includes


defaults:
  - values:
      logosnav: true


plugins:
  - jemoji

menu:
  - title: About Us
    url: about_us
  - title: Training
    url: traning
  - title: Tools
    url: tools
  - title: Standards
    url: standards
  - title: FAQ
    url: faq



avatar: "./logos/SCO.png"
