
# github-pages mandatory configuration
domain: czarnewski.github.io
url: https://czarnewski.github.io/sco-community
baseurl: /sco-community
repository: czarnewski/sco-community

# Build settings
markdown: kramdown
# theme: minima

# Name of the website
title: ELIXIR SCO Community

# Where things are
layouts_dir: ./_layouts
includes_dir: ./_includes


defaults:
  - values:
      logosnav: true


plugins:
  - jemoji


menu:
  - title: ABOUT US
    path: about_us
    submenu:
      - title: Submenu 1
        url: training
      - title: Submenu 2
        url: training

  - title: TRAINING
    url: training
    submenu:
      - title: Submenu 1
        url: training
      - title: Submenu 2
        url: training

  - title: TOOLS
    url: tools
    submenu:
      - title: Submenu 1
        url: training
      - title: Submenu 2
        url: training

  - title: DATA
    url: data
    submenu:
      - title: Submenu 1
        url: training
      - title: Submenu 2
        url: training

  - title: FAQ
    url: faq
    submenu:
      - title: Submenu 1
        url: training
      - title: Submenu 2
        url: training


avatar: "./logos/ELIXIR/SCO.png"



countries1:
  - title: Belgium
    url: belgium
  - title: Czech Republic
    url: czech-republic
  - title: Denmark
    url: denmark
  - title: EMBL-EBI
    url: embl-ebi
  - title: Estonia
    url: estonia
  - title: Finland
    url: finland
  - title: France
    url: france
  - title: Germany
    url: germany

countries2:
  - title: Greece
    url: greece
  - title: Hungary
    url: hungary
  - title: Ireland
    url: ireland
  - title: Israel
    url: israel
  - title: Italy
    url: italy
  - title: Luxenbourg
    url: luxenbourg
  - title: Norway
    url: norway
  - title: Portugal
    url: portugal

countries3:
  - title: Slovenia
    url: slovenia
  - title: Spain
    url: spain
  - title: Sweden
    url: sweden
  - title: Switzerland
    url: switzerland
  - title: United Kigndom
    url: uk
  - title: Cyprus (observer)
    url: cyprus












#
